[package]
name = "moxie2-macros"
version = "0.1.0"
authors = ["zetanumbers <zeta0.114942@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.60", features = ["visit-mut", "extra-traits"] }
quote = "1.0.8"
proc-macro2 = "1.0.24"
